# vim: set ft=ansible

- name: register list of machinesets
  shell: "oc get machineset -n openshift-machine-api"
  register: infra_machineset_exists

# stdout will have the word infra if there's already an infra machineset
# if there is one, we don't create any

- name: create infra machineset(s)
  script: files/infra.sh {{ item }}
  loop: "{{ azs }}"
  when: '"infra" not in infra_machineset_exists.stdout'

# move router (doesn't work yet)

- name: move monitoring onto infra nodes
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: cluster-monitoring-config
        namespace: openshift-monitoring
      data:
        config.yaml: |+
          alertmanagerMain:
            nodeSelector:
              node-role.kubernetes.io/infra: ""
          prometheusK8s:
            nodeSelector:
              node-role.kubernetes.io/infra: ""
          prometheusOperator:
            nodeSelector:
              node-role.kubernetes.io/infra: ""
          grafana:
            nodeSelector:
              node-role.kubernetes.io/infra: ""
          k8sPrometheusAdapter:
            nodeSelector:
              node-role.kubernetes.io/infra: ""
          kubeStateMetrics:
            nodeSelector:
              node-role.kubernetes.io/infra: ""
          telemeterClient:
            nodeSelector:
              node-role.kubernetes.io/infra: ""